// <auto-generated />
using Car_Mod_net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Mod_net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712175211_AddDescriptionToModPart")]
    partial class AddDescriptionToModPart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Car_Mod_net.Models.ModPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Body Kit",
                            Description = "Ultra-lightweight aerospace-grade carbon fiber hood with integrated aerodynamic vents. Optimizes engine cooling and reduces front-axle weight.",
                            ImageUrl = "/images/carbon-hood.jpg",
                            Name = "Vented Carbon Fiber Hood",
                            Price = 1850.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Wheels",
                            Description = "Track-ready monoblock forged aluminum wheels designed to withstand intense lateral load. Finished in raw matte obsidian.",
                            ImageUrl = "/images/forged-wheels.jpg",
                            Name = "Forged Monoblock Track Wheels",
                            Price = 4200.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Custom Paint",
                            Description = "Multi-layered premium vinyl wrap with a liquid chrome satin finish. Protects original paint while delivering an aggressive, reflective styling.",
                            ImageUrl = "/images/chrome-wrap.jpg",
                            Name = "Satin Liquid Chrome Wrap",
                            Price = 3500.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Body Kit",
                            Description = "Adjustable dual-plane carbon fiber rear wing engineered to maximize downforce and stability at high speeds.",
                            ImageUrl = "/images/rear-wing.jpg",
                            Name = "Carbon Rear Wing Spoiler",
                            Price = 2200.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Window Tint",
                            Description = "Next-gen nano-ceramic film providing up to 99% infrared heat rejection and dark stealth styling without signal interference.",
                            ImageUrl = "/images/stealth-tint.jpg",
                            Name = "Ceramic Infrared Stealth Tint",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Exhaust",
                            Description = "Titanium active-valve catback exhaust system with vacuum-controlled valves. Features blue-burnt tips and delivers a raw, unrestrained acoustic profile.",
                            ImageUrl = "/images/titanium-exhaust.jpg",
                            Name = "Titanium Active Valve Exhaust",
                            Price = 3800.00m
                        });
                });

            modelBuilder.Entity("Car_Mod_net.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Honda",
                            Model = "Civic Type R",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Make = "Porsche",
                            Model = "911 GT3 RS",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Make = "Nissan",
                            Model = "GT-R (R35)",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Make = "Toyota",
                            Model = "GR Supra",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Car_Mod_net.Models.VehicleModPart", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModPartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId", "ModPartId");

                    b.HasIndex("ModPartId");

                    b.ToTable("VehicleModParts");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            ModPartId = 1
                        },
                        new
                        {
                            VehicleId = 3,
                            ModPartId = 1
                        },
                        new
                        {
                            VehicleId = 4,
                            ModPartId = 1
                        },
                        new
                        {
                            VehicleId = 1,
                            ModPartId = 2
                        },
                        new
                        {
                            VehicleId = 2,
                            ModPartId = 2
                        },
                        new
                        {
                            VehicleId = 3,
                            ModPartId = 2
                        },
                        new
                        {
                            VehicleId = 4,
                            ModPartId = 2
                        },
                        new
                        {
                            VehicleId = 1,
                            ModPartId = 3
                        },
                        new
                        {
                            VehicleId = 2,
                            ModPartId = 3
                        },
                        new
                        {
                            VehicleId = 3,
                            ModPartId = 3
                        },
                        new
                        {
                            VehicleId = 4,
                            ModPartId = 3
                        },
                        new
                        {
                            VehicleId = 2,
                            ModPartId = 4
                        },
                        new
                        {
                            VehicleId = 3,
                            ModPartId = 4
                        },
                        new
                        {
                            VehicleId = 4,
                            ModPartId = 4
                        },
                        new
                        {
                            VehicleId = 1,
                            ModPartId = 5
                        },
                        new
                        {
                            VehicleId = 2,
                            ModPartId = 5
                        },
                        new
                        {
                            VehicleId = 3,
                            ModPartId = 5
                        },
                        new
                        {
                            VehicleId = 4,
                            ModPartId = 5
                        },
                        new
                        {
                            VehicleId = 2,
                            ModPartId = 6
                        },
                        new
                        {
                            VehicleId = 3,
                            ModPartId = 6
                        },
                        new
                        {
                            VehicleId = 4,
                            ModPartId = 6
                        });
                });

            modelBuilder.Entity("Car_Mod_net.Models.VehicleModPart", b =>
                {
                    b.HasOne("Car_Mod_net.Models.ModPart", "ModPart")
                        .WithMany("VehicleModParts")
                        .HasForeignKey("ModPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Mod_net.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleModParts")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModPart");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Car_Mod_net.Models.ModPart", b =>
                {
                    b.Navigation("VehicleModParts");
                });

            modelBuilder.Entity("Car_Mod_net.Models.Vehicle", b =>
                {
                    b.Navigation("VehicleModParts");
                });
#pragma warning restore 612, 618
        }
    }
}
